#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "nord"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[custom_plugins]]
name = 'iamcco/coc-flutter'
merged = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_method = "coc"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'ctrlspace'
enable = false

[[layers]]
name = 'denite'
enable = false

[[layers]]
name = 'exprfold'

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'github'

[[layers]]
name = 'lang#dart'

[[layers]]
name = 'lang#dockerfile'

[[layers]]
name = 'lang#elixer'

[[layers]]
name = 'lang#elm'

[[layers]]
name = 'lang#erlang'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#graphql'

[[layers]]
name = 'lang#haskell'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#java'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#json'

[[layers]]
name = 'lang#kotlin'

[[layers]]
name = 'lang#ocaml'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'lang#php'

[[layers]]
name = 'lang#purescript'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#sql'

[[layers]]
name = 'lang#swift'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#vue'

[[layers]]
name = 'leaderf'
enable = false

[[layers]]
name = 'lsp'

[[layers]]
name = 'operator'

[[layers]]
name = 'test'

[[layers]]
name = 'tmux'
